---
title: "scratchwork-edwardho01"
author: "Edward Ho"
date: "2022-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Packages and Data

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate) #dealing with dates, and time series aspect 
library(Rbeast) #used for change-point detection
library(changepoint) #used for change-point detection
library(changepoint.np) #used for change-point nonparemetric
library(zoo)
processed_data <- read_csv('data/processed_data.csv')
```

## Processing Data

```{r}
processed_data$DATE <- as.Date(processed_data$DATE, "%Y/%m/%d") # change date from characters to date element
data <- tibble(processed_data$DATE,processed_data$unemploy_rate_la) %>%
  rename("unemploy_rate_la" = "processed_data$unemploy_rate_la", "date" = "processed_data$DATE")
plot(unemploy_rate_la ~ date, data, xaxt = "n", type = "l")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
